#!/usr/bin/env python3
"""Generate the CP932 -> UTF-16 table used by the TH11 glyph atlas.

Mirrors th11_web/scripts/prepare-fonts.mjs: index n < 256 is a single byte,
otherwise the byte pair (n >> 8, n & 255). Anything that does not decode to
exactly one UTF-16 unit maps to U+30FB, like the upstream baker.
Usage: gen_cp932.py out.inc
"""
import sys

values = []
for n in range(65536):
    raw = bytes([n]) if n < 256 else bytes([n >> 8, n & 255])
    try:
        text = raw.decode("cp932")
    except UnicodeDecodeError:
        text = ""
    values.append(ord(text) if len(text) == 1 and ord(text) < 0x10000 else 0x30FB)

with open(sys.argv[1], "w") as out:
    out.write("// Generated by scripts/gen_cp932.py - do not edit.\n")
    out.write("static const u16 cp932_map[65536]={\n")
    for i in range(0, 65536, 16):
        out.write(",".join(str(v) for v in values[i:i + 16]) + ",\n")
    out.write("};\n")
