#include "FontBaker.hpp"
#include "Platform.hpp"
#include <ft2build.h>
#include FT_FREETYPE_H
#include FT_SYNTHESIS_H
#include FT_BITMAP_H
#include <algorithm>
#include <cmath>
#include <memory>
#ifdef __SWITCH__
#include <switch.h>
#endif

namespace th11::host {
namespace {
#include "cp932_table.inc" // generated by scripts/gen_cp932.py: cp932_map[65536]

struct Face {
    FT_Face face=nullptr;std::string name;
    ~Face(){if(face)FT_Done_Face(face);}
};
struct Library {FT_Library ft=nullptr;~Library(){if(ft)FT_Done_FreeType(ft);}};

template<class T>void put(std::vector<u8>& b,size_t at,T v){std::memcpy(b.data()+at,&v,sizeof v);}

// Coverage classes 1..16 = alpha/16. The blend table maps (class, 4-bit
// background channel, 8-bit text colour channel) -> 4-bit result, the shape
// GlyphAtlas::draw expects (upstream: GDI-measured classes).
constexpr u32 classes=16;
u8 coverage_class(u32 alpha){return alpha?u8(std::min<u32>(classes,(alpha*classes+254)/255)):0;}

struct Request {u32 height,weight;bool mincho;};
// th11 1.00a 444480 CreateFont parameters (upstream prepare-fonts.mjs).
constexpr Request requests[4]{{32,400,false},{32,600,true},{15,700,false},{15,700,true}};

std::unique_ptr<Face> open_file(FT_Library ft,const std::string& path,long index=0){
    if(!exists(path))return nullptr;auto f=std::make_unique<Face>();
    if(FT_New_Face(ft,path.c_str(),index,&f->face)){f->face=nullptr;return nullptr;}
    f->name=path;return f;
}
#ifdef __SWITCH__
std::unique_ptr<Face> open_shared(FT_Library ft){
    static bool tried=false;static PlFontData font{};
    if(!tried){tried=true;if(R_FAILED(plInitialize(PlServiceType_User))||R_FAILED(plGetSharedFontByType(&font,PlSharedFontType_Standard)))font.address=nullptr;}
    if(!font.address||!font.size)return nullptr;auto f=std::make_unique<Face>();
    if(FT_New_Memory_Face(ft,static_cast<const FT_Byte*>(font.address),FT_Long(font.size),0,&f->face)){f->face=nullptr;return nullptr;}
    f->name="Switch shared font (Standard)";return f;
}
#endif

bool bake(FT_Library ft,Face& face,const Request& r,u32 slot,const std::vector<u16>& chars,std::vector<u8>& out,const std::function<void(float)>& progress){
    // Positive lfHeight = cell height (ascent + descent). MS Gothic/Mincho
    // have cell == em, so FreeType's CELL request matches GDI exactly. Other
    // faces (the system-font fallback) have taller cells; size those by em and
    // place the baseline at MS Gothic's ascent (220/256 em) instead.
    const auto* f=face.face;const bool ms_metrics=FT_IS_SFNT(f)&&f->ascender-f->descender==f->units_per_EM;
    FT_Size_RequestRec size{ms_metrics?FT_SIZE_REQUEST_TYPE_CELL:FT_SIZE_REQUEST_TYPE_NOMINAL,0,FT_Long(r.height)*64,0,0};
    if(FT_Request_Size(face.face,&size))return false;
    const i32 ascent=ms_metrics?i32(std::lround(face.face->size->metrics.ascender/64.0)):i32(std::lround(r.height*220.0/256.0));
    const bool bold=r.weight>=600;
    struct Glyph {u32 code;i16 advance,left,top;u16 width,height;std::vector<u8> coverage;};
    std::vector<Glyph> glyphs;glyphs.reserve(chars.size());
    for(const u16 code:chars){
        if(progress&&glyphs.size()%256==0)progress((float(slot)+float(glyphs.size())/float(chars.size()))/4.f);
        Glyph g{code,0,0,0,0,0,{}};
        const FT_UInt index=FT_Get_Char_Index(face.face,code);
        if(index&&!FT_Load_Glyph(face.face,index,FT_LOAD_DEFAULT|FT_LOAD_TARGET_NORMAL)){
            auto* slot_=face.face->glyph;
            if(bold)FT_GlyphSlot_Embolden(slot_);
            if(slot_->format!=FT_GLYPH_FORMAT_BITMAP)FT_Render_Glyph(slot_,FT_RENDER_MODE_NORMAL);
            FT_Bitmap gray;FT_Bitmap_Init(&gray);
            const bool converted=slot_->bitmap.pixel_mode!=FT_PIXEL_MODE_GRAY;
            if(converted&&FT_Bitmap_Convert(ft,&slot_->bitmap,&gray,1)){FT_Bitmap_Done(ft,&gray);continue;}
            const FT_Bitmap& bmp=converted?gray:slot_->bitmap;
            // FT_Bitmap_Convert leaves mono pixels as 0/1; scale to 0..255.
            const u32 scale=converted&&gray.num_grays==2?255:1;
            g.advance=i16(std::lround(slot_->advance.x/64.0));
            const u32 w=std::min<u32>(bmp.width,128),h=std::min<u32>(bmp.rows,128);
            // Trim to the painted box like the GDI baker does.
            u32 x0=w,y0=h,x1=0,y1=0;
            for(u32 y=0;y<h;++y)for(u32 x=0;x<w;++x)if(coverage_class(bmp.buffer[y*bmp.pitch+x]*scale)){x0=std::min(x0,x);y0=std::min(y0,y);x1=std::max(x1,x+1);y1=std::max(y1,y+1);}
            if(x1>x0&&y1>y0){
                g.width=u16(x1-x0);g.height=u16(y1-y0);g.left=i16(slot_->bitmap_left+i32(x0));g.top=i16(ascent-slot_->bitmap_top+i32(y0));
                g.coverage.resize(size_t(g.width)*g.height);
                for(u32 y=0;y<g.height;++y)for(u32 x=0;x<g.width;++x)g.coverage[y*g.width+x]=coverage_class(bmp.buffer[(y0+y)*bmp.pitch+x0+x]*scale);
            }
            FT_Bitmap_Done(ft,&gray);
        }
        if(!g.advance&&!g.width&&code!=0x30fb&&code!=0x20&&code!=0x3000)continue; // missing glyph -> falls back to U+30FB
        glyphs.push_back(std::move(g));
    }
    // T11G v1: 32-byte header, 20-byte records sorted by code, coverage bytes.
    const u32 offset=32+u32(glyphs.size())*20;u32 total=offset;for(const auto& g:glyphs)total+=u32(g.coverage.size());
    out.assign(total,0);std::memcpy(out.data(),"T11G",4);
    const u32 header[7]{1,slot,r.height,u32(glyphs.size()),offset,total,0};for(u32 i=0;i<7;++i)put(out,4+i*4,header[i]);
    u32 at=offset;
    for(size_t i=0;i<glyphs.size();++i){const auto& g=glyphs[i];const size_t p=32+i*20;
        put(out,p,g.code);put(out,p+4,at);put(out,p+8,g.advance);put(out,p+10,g.left);put(out,p+12,g.top);put(out,p+14,g.width);put(out,p+16,g.height);
        std::memcpy(out.data()+at,g.coverage.data(),g.coverage.size());at+=u32(g.coverage.size());}
    return true;
}
}

const u16* cp932_table(){return cp932_map;}

bool bake_fonts(BakedFonts& result,std::string& error,const std::function<void(float)>& progress){
    Library lib;if(FT_Init_FreeType(&lib.ft)){error="FreeType initialisation failed";return false;}
    const auto& p=paths();
    auto gothic=open_file(lib.ft,p.data_file("msgothic.ttc"));
    auto mincho=open_file(lib.ft,p.data_file("msmincho.ttc"));
#ifdef __SWITCH__
    std::unique_ptr<Face> shared;if(!gothic||!mincho)shared=open_shared(lib.ft);
#else
    std::unique_ptr<Face> shared;
    if(!gothic||!mincho)for(const char* c:{"/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc","/usr/share/fonts/truetype/fonts-japanese-gothic.ttf","/usr/share/fonts/truetype/takao-gothic/TakaoGothic.ttf"})if((shared=open_file(lib.ft,c)))break;
#endif
    Face* faces[2]{gothic?gothic.get():mincho?mincho.get():shared.get(),mincho?mincho.get():gothic?gothic.get():shared.get()};
    if(!faces[0]){error="No font found. Copy msgothic.ttc (from Windows) next to th11.dat.";return false;}
    result.source=std::string("gothic=")+faces[0]->name+" mincho="+faces[1]->name;

    // Character set exactly as the upstream baker: every CP932 code that
    // decodes to one printable UTF-16 unit, plus the U+30FB fallback.
    std::vector<u16> chars;{std::vector<bool> seen(65536);
        for(u32 n=0;n<65536;++n){const u16 c=cp932_map[n];if(c>=32&&c!=127&&c!=0x30fb)seen[c]=true;}seen[0x30fb]=true;
        for(u32 c=0;c<65536;++c)if(seen[c])chars.push_back(u16(c));}
    for(u32 slot=0;slot<4;++slot)if(!bake(lib.ft,*faces[requests[slot].mincho?1:0],requests[slot],slot,chars,result.files[slot],progress)){error="Unable to rasterise font "+std::to_string(slot);return false;}

    auto& map=result.files[4];map.resize(131072);std::memcpy(map.data(),cp932_map,131072);
    auto& blend=result.files[5];blend.assign((classes+1)*4096,0);
    for(u32 id=1;id<=classes;++id)for(u32 background=0;background<16;++background)for(u32 foreground=0;foreground<256;++foreground){
        const double a=double(id)/classes,text=foreground*15.0/255.0;
        blend[id*4096+background*256+foreground]=u8(std::clamp<long>(std::lround(background*(1-a)+text*a),0,15));
    }
    return true;
}
}
